INSERT INTO Transaction_Types (Id, name) VALUES (1, "Debit");
INSERT INTO Transaction_Types (Id, name) VALUES (2, "Credit")

INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (1, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 1");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (2, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 2");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (3, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 3");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (4, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 4");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (5, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 5");