INSERT INTO users (user_name, email, password_hash) VALUES ("cikro", "niorkic@gmail.com", "password")

INSERT INTO Account_Types (name) VALUES ("Asset");
INSERT INTO Account_Types (name) VALUES ("Liability");
INSERT INTO Account_Types (name) VALUES ("Expense");
INSERT INTO Account_Types (name) VALUES ("Revenue");

INSERT INTO Currencies (CODE, name) VALUES ("CAD", "Canadian");

INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 1", "Test Account 1",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 2", "Test Account 2",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 3", "Test Account 3",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 4", "Test Account 4",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 5", "Test Account 5",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 6", "Test Account 6",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 7", "Test Account 7",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 8", "Test Account 8",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 9", "Test Account 9",0, 1, "CAD");
INSERT INTO Accounts (user_id, name, description, balance, type, currency_code) VALUES (1,"test 10", "Test Account 10",0, 1, "CAD");

INSERT INTO Transaction_Types (Id, name) VALUES (1, "Debit");
INSERT INTO Transaction_Types (Id, name) VALUES (2, "Credit")

INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);
INSERT INTO Journal_Entries (user_id, amount) VALUES (1, 1337);

INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (1, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 1");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (2, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 2");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (3, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 3");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (4, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 4");
INSERT INTO Transactions (journal_entry, user_id, account_id, type, amount, transaction_date, notes) VALUES (5, 1, 5, 1, 1337, "2022-04-02", "AutoGenerated 5");