SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS account_types;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS currencies;
DROP TABLE IF EXISTS journal_entries;
DROP TABLE IF EXISTS transaction_types;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;